apiVersion: v1
kind: Service
metadata:
  name: nextjs-myapp-service
  # namespace: nextjs-3000
spec:
  # type: ClusterIP
  selector:
    app: nextjs-myapp
  ports:
    - protocol: TCP
      port: 3000